FROM microsoft/dotnet
WORKDIR /app
COPY . /app
CMD ["dotnet","run"]

#docker build -t jack/userapi:dev .
#dotnet run --name userapidemo jack/userapi:dev
#docker run --name userapidemo jack/userapi:dev
#docker ps 
#docker exec -it id bash
#cd/
#ls